#!/usr/bin/env bash
# ── Open Fabric Studio — Installer ────────────────────────────────────────────
# Generates secrets, writes .env, pulls images, and starts the stack.
#
# Usage:
#   chmod +x install.sh
#   ./install.sh
#
# To upgrade to a newer release:
#   docker compose pull
#   docker compose up -d

set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
RESET='\033[0m'

# Always resolve .env and docker-compose.yml relative to this script, regardless
# of the directory from which the installer was invoked.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

echo ""
echo -e "${BOLD}  Open Fabric Studio — Installer${RESET}"
echo "  ─────────────────────────────────"
echo ""

# ── Prerequisite checks ───────────────────────────────────────────────────────
check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${RED}✗ '$1' is required but not found.${RESET}"
    echo "  Install Docker: https://docs.docker.com/get-docker/"
    exit 1
  fi
}

check_command docker
check_command openssl

# Verify Docker Compose v2 is available (bundled with modern Docker)
if ! docker compose version &>/dev/null; then
  echo -e "${RED}✗ Docker Compose v2 is required.${RESET}"
  echo "  Update Docker Desktop or install the compose plugin."
  exit 1
fi

# ── Secret generation ─────────────────────────────────────────────────────────
if [ -f .env ]; then
  echo -e "${YELLOW}⚠  .env already exists — skipping secret generation.${RESET}"
  echo "   Delete .env and re-run this script to regenerate secrets."
  echo "   Note: regenerating secrets will invalidate all saved device credentials."
  echo ""
else
  echo "  Generating secrets…"

  POSTGRES_PASSWORD=$(openssl rand -hex 32)
  JWT_SECRET=$(openssl rand -hex 32)
  CREDENTIAL_ENCRYPTION_KEY=$(openssl rand -hex 32)

  cat > .env <<EOF
# Open Fabric Studio — auto-generated by install.sh
# WARNING: Do not change CREDENTIAL_ENCRYPTION_KEY after installation.
#          Doing so will break access to all saved device credentials.

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY}
APP_PORT=80
CORS_ORIGINS=http://localhost
EOF

  echo -e "${GREEN}  ✓ Secrets written to .env${RESET}"
  echo -e "${YELLOW}  ⚠  Keep .env safe and backed up — losing it means losing${RESET}"
  echo -e "${YELLOW}     access to all stored device credentials.${RESET}"
  echo ""
fi

# ── Pull images ───────────────────────────────────────────────────────────────
echo "  Pulling Open Fabric Studio images…"
docker compose pull
echo ""

# ── Start the stack ───────────────────────────────────────────────────────────
echo "  Starting services…"
if ! docker compose up -d --wait --wait-timeout 180; then
  echo ""
  echo -e "${RED}✗ Open Fabric Studio failed to become healthy.${RESET}"
  echo "  Container status:"
  docker compose ps --all || true
  echo ""
  echo "  Backend and database logs:"
  docker compose logs --no-color --tail=100 backend db || true
  exit 1
fi
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
APP_PORT=$(grep -E '^APP_PORT=' .env | cut -d= -f2 || echo 80)

echo -e "${GREEN}${BOLD}  ✓ Open Fabric Studio is running!${RESET}"
echo ""
echo "  Access the application at:"
echo -e "  ${BOLD}  http://localhost:${APP_PORT}${RESET}"
echo ""
echo "  Useful commands:"
echo "    docker compose ps          — check service status"
echo "    docker compose logs -f     — view live logs"
echo "    docker compose down        — stop all services"
echo "    docker compose pull && docker compose up -d  — upgrade"
echo ""
